install with mode
Co-authored-by: Jörg Behrmann <behrmann@physik.fu-berlin.de>

diff --git a/src/kernel-install/40-early-cpio.install b/src/kernel-install/40-early-cpio.install
--- a/src/kernel-install/40-early-cpio.install
+++ b/src/kernel-install/40-early-cpio.install
@@ -25,12 +25,12 @@ COMMAND="${1:?}"
 if [ "$COMMAND" = "add" ]; then
     for ucode in "intel-ucode.img" "amd-ucode.img" "intel-uc.img" "amd-uc.img" "early_ucode.cpio" "microcode.cpio"; do
         for dir in "$KERNEL_INSTALL_BOOT_ROOT" "/boot"; do
-        if [ -f "${dir}/${ucode}" ]; then
-            install "${dir}/${ucode}" "${KERNEL_INSTALL_STAGING_AREA}/early-cpio-${ucode}" || {
-                echo "Error: could not copy '$ucode' to the staging area." >&2
-                exit 1
-            }
-        fi
+            if [ -f "${dir}/${ucode}" ]; then
+                install -m 0644 "${dir}/${ucode}" "${KERNEL_INSTALL_STAGING_AREA}/early-cpio-${ucode}" || {
+                    echo "Error: could not copy '$ucode' to the staging area." >&2
+                    exit 1
+                }
+            fi
         done
     done
 fi
