correct PCR snippet

diff --git a/src/kernel-install/60-ukify.install b/src/kernel-install/60-ukify.install
--- a/src/kernel-install/60-ukify.install
+++ b/src/kernel-install/60-ukify.install
@@ -20,19 +20,12 @@
 
 set -e
 
-# TODO
-# log messages
-# Measure and output '/etc/systemd/tpm2-pcr-signature.json'  
-# better home for UKI_PCRPRIVATEKEY
-# detect available PCR banks
-# phases
-# sections
-
 COMMAND="${1:?}"
 KERNEL_VERSION="${2:?}"
 KERNEL_IMAGE="$4"
 INITRD_OPTIONS_SHIFT=4
 
+# Default paths
 DEFAULT_PCRPRIVATEKEY="/etc/systemd/tpm2-pcr-private.pem" 
 DEFAULT_PCRPUBLICKEY="/etc/systemd/tpm2-pcr-public-key.pem"
 
@@ -113,18 +106,21 @@ if [ "$COMMAND" = "add" ]; then
 
     # TODO --section=NAME:TEXT|@PATH    
     
-    # Add PCR keys if supplied, or detected. Public key is optional. Otherwise create the keys.
+    # PCR keys 
+    # Check if a PCR private key is supplied
     if [ -n "$UKI_PCRPRIVATEKEY" ]; then
-        [ -f "$UKI_PCRPRIVATEKEY" ] || {
+        [ -f "$UKI_PCRPRIVATEKEY" ] || { 
             echo "Error: $UKI_PCRPRIVATEKEY not a file." >&2
             exit 1
         }
+        # Check if PCR public key (optional) is also supplied
         if [ -n "$UKI_PCRPUBLICKEY" ]; then
             [ -f "$UKI_PCRPUBLICKEY" ] || {
-            echo "Error: $UKI_PCRPUBLICKEY not a file." >&2
-            exit 1
-        }
-	fi
+                echo "Error: $UKI_PCRPUBLICKEY not a file." >&2
+                exit 1
+            }
+        fi
+    # If PCR private key is not supplied, check if default keys exist and use them, else generate new ones
     elif [ -f "$DEFAULT_PCRPRIVATEKEY" ]; then
         UKI_PCRPRIVATEKEY="$DEFAULT_PCRPRIVATEKEY"
         if [ -f "$DEFAULT_PCRPUBLICKEY" ]; then
@@ -137,8 +133,12 @@ if [ "$COMMAND" = "add" ]; then
         }
         chmod 400 "$DEFAULT_PCRPRIVATEKEY"
         openssl rsa -pubout -in "$DEFAULT_PCRPRIVATEKEY" -out "$DEFAULT_PCRPUBLICKEY"
+        # Set the new keys as PCR keys
+        [ -f "$DEFAULT_PCRPRIVATEKEY" ] && UKI_PCRPRIVATEKEY="$DEFAULT_PCRPRIVATEKEY"
+        [ -f "$DEFAULT_PCRPUBLICKEY" ] && UKI_PCRPUBLICKEY="$DEFAULT_PCRPUBLICKEY"
     fi
-    
+
+    # Add the supplied/default/generated PCR keys as arguments
     [ -n "$UKI_PCRPRIVATEKEY" ] && [ -n "$UKI_PCRPUBLICKEY" ] && ARGS="$ARGS --pcr-private-key=$UKI_PCRPRIVATEKEY --pcr-public-key=$UKI_PCRPUBLICKEY"
     
     # TODO --phases (could be included above)
@@ -149,7 +149,7 @@ if [ "$COMMAND" = "add" ]; then
     # Add SecureBoot keys if detected
     if [ -n "$UKI_SBKEY" ] && [ -n "$UKI_SBCERT" ]; then
         ARGS="$ARGS --secureboot-private-key=$UKI_SBKEY --secureboot-certificate=$UKI_SBCERT"
-	fi
+    fi
 	
     # Signing engine
     [ -n "$UKI_SIGNENGINE" ] && ARGS="$ARGS --signing-engine=$UKI_SIGNENGINE"
@@ -161,7 +161,7 @@ if [ "$COMMAND" = "add" ]; then
                 ;;
             [Nn]*) ARGS="$ARGS --no-sign-kernel"
                 ;;
-            *) [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && echo "Skipping, UKI_SIGNKERNEL must be set to 'Y' or 'N'"
+            *) [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && echo "Invalid 'UKI_SIGNKERNEL' value (must be set to 'Y' or 'N')"
                 ;;
         esac
     fi
