Improve kernel-install support for initrd files.
The current support in kernel-install for initrd images doesn't copy
over the initrd file or allow a means for it to be specified (it
requires a specific filename in a particular directory).

This patchset adds support for (optionally) providing the name of
initial ramdisk file to copied over and used by kernel-install.

Signed-off-by: Mike Auty <mike.auty@gmail.com>

diff --git a/src/kernel-install/90-loaderentry.install b/src/kernel-install/90-loaderentry.install
--- a/src/kernel-install/90-loaderentry.install
+++ b/src/kernel-install/90-loaderentry.install
@@ -6,6 +6,7 @@ COMMAND="$1"
 KERNEL_VERSION="$2"
 BOOT_DIR_ABS="$3"
 KERNEL_IMAGE="$4"
+INITRD_FILE="$5"
 
 if ! [[ $KERNEL_INSTALL_MACHINE_ID ]]; then
     exit 0
@@ -81,6 +82,15 @@ cp "$KERNEL_IMAGE" "$BOOT_DIR_ABS/linux" &&
     echo "Could not copy '$KERNEL_IMAGE to '$BOOT_DIR_ABS/linux'." >&2
     exit 1
 }
+
+if [[ -f "${INITRD_IMAGE}" ]]; then
+    cp "${INITRD_IMAGE}" "$BOOT_DIR_ABS/initd" &&
+        chown root:root "$BOOT_DIR_ABS/initrd" &&
+        chmod 0644 "$BOOT_DIR_ABS/initrd" || {
+         echo "Could not copy '$INITRD_FILE' to '$BOOT_DIR_ABS/initrd'." >&2
+         exit 1
+    }
+fi
 
 mkdir -p "${LOADER_ENTRY%/*}" || {
     echo "Could not create loader entry directory '${LOADER_ENTRY%/*}'." >&2
