kernel-install: k-i already creates $ENTRY_DIR_ABS, no need to do it again

diff --git a/src/kernel-install/90-loaderentry.install b/src/kernel-install/90-loaderentry.install
--- a/src/kernel-install/90-loaderentry.install
+++ b/src/kernel-install/90-loaderentry.install
@@ -78,12 +78,8 @@ else
 fi
 
 if ! [ -d "$ENTRY_DIR_ABS" ]; then
-    if [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ]; then
-        echo "+mkdir -v -p $ENTRY_DIR_ABS"
-        mkdir -v -p "$ENTRY_DIR_ABS"
-    else
-        mkdir -p "$ENTRY_DIR_ABS"
-    fi
+    echo "Error: entry directory '$ENTRY_DIR_ABS' does not exist" >&2
+    exit 1
 fi
 
 install -g root -o root -m 0644 "$KERNEL_IMAGE" "$ENTRY_DIR_ABS/linux" || {
