mkosi: Check for failures by mounting again
We rely on vsock to communicate the exit status back to us from the
VM but vsock in Github Actions is broken so let's switch back to
mounting for now.

diff --git a/.github/workflows/mkosi.yml b/.github/workflows/mkosi.yml
--- a/.github/workflows/mkosi.yml
+++ b/.github/workflows/mkosi.yml
@@ -124,3 +124,7 @@ jobs:
 
     - name: Boot ${{ matrix.distro }} QEMU
       run: timeout -k 30 10m mkosi --debug qemu
+
+    # vsock in Github Actions with qemu is broken so for now we check for failures manually.
+    - name: Check ${{ matrix.distro }} QEMU
+      run: sudo mkosi shell bash -c "[[ -e /testok ]] || { cat /failed-services; exit 1; }"
